# Generated by Django 5.2.16 on 2026-09-20 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_listing_is_quick_sale_listing_quick_sale_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('hub_type', models.CharField(choices=[('CAMPUS', 'University / College Campus'), ('TOWN', 'Town / Suburb / Commercial Center')], default='CAMPUS', max_length=20)),
                ('region', models.CharField(default='Central Region', max_length=50)),
                ('icon', models.CharField(default='bi-mortarboard-fill', help_text='Bootstrap icon class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Communities',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='hostel',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostels', to='marketplace.community'),
        ),
        migrations.AddField(
            model_name='listing',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='marketplace.community'),
        ),
    ]
