# Generated by Django 5.2.16 on 2026-09-20 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_community_hostel_community_listing_community'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('offered_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('counter_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('buyer_note', models.CharField(blank=True, default='', max_length=255)),
                ('seller_note', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review ⏳'), ('COUNTERED', 'Counter Offer ⚡'), ('ACCEPTED', 'Offer Accepted 🎉'), ('DECLINED', 'Declined ❌'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('deal_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_made', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='marketplace.listing')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
