# Generated by Django 5.2.16 on 2026-09-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_offer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Housing & Rental', 'verbose_name_plural': 'Housing & Rentals'},
        ),
        migrations.AddField(
            model_name='hostel',
            name='billing_cycle',
            field=models.CharField(choices=[('PER_MONTH', 'Per Month'), ('PER_SEMESTER', 'Per Semester')], default='PER_SEMESTER', max_length=20, verbose_name='Billing Cycle'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='has_parking',
            field=models.BooleanField(default=False, verbose_name='Parking Space Available'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='has_security',
            field=models.BooleanField(default=False, verbose_name='Gated Compound / 24/7 Security'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='has_water_reserve',
            field=models.BooleanField(default=False, verbose_name='Water Reserve / Tank / Borehole'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='has_yaka_meter',
            field=models.BooleanField(default=False, verbose_name='Prepaid Yaka Electricity Meter'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='is_self_contained',
            field=models.BooleanField(default=False, verbose_name='Self-Contained (Private Washroom)'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='rental_type',
            field=models.CharField(choices=[('HOSTEL', 'Student Hostel (Single / Shared)'), ('BEDSITTER', 'Bedsitter & Studio Apartment'), ('RESIDENTIAL', '1 & 2 Bedroom Residential Rental'), ('COMMERCIAL', 'Commercial Space & Market Stall')], default='HOSTEL', max_length=30, verbose_name='Rental Category'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed info about the rental unit, rules, terms, etc.', null=True),
        ),
    ]
