# Generated by Django 5.2.17 on 2026-09-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_alter_hostel_options_hostel_billing_cycle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Moderation'), ('ACTIVE', 'Active'), ('SOLD', 'Sold'), ('REJECTED', 'Rejected'), ('REMOVED', 'Removed by Admin'), ('SUSPENDED', 'Suspended (Subscription Expired)')], default='ACTIVE', max_length=20),
        ),
    ]
