# Generated by Django 5.2.17 on 2026-09-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_listing_suspended_at_alter_listing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Moderation'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended (Subscription Expired)')], default='PENDING', max_length=20),
        ),
    ]
