# Generated by Django 5.2.17 on 2026-09-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscriptionplan_duration_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('QUICK_SALE', 'Quick Sale'), ('HOSTEL', 'Hostel')], max_length=10, unique=True),
        ),
    ]
